# Generated by Django 3.2.9 on 2021-11-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusproducttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statusproducttranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_status',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='KidsStepShop.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='StatusProduct',
        ),
        migrations.DeleteModel(
            name='StatusProductTranslation',
        ),
    ]
