# Generated by Django 3.2.9 on 2021-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0003_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusordertranslation',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusordertranslation',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
