# Generated by Django 3.2.9 on 2021-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0004_auto_20211124_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusordertranslation',
            name='status',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
