# Generated by Django 3.2.9 on 2021-11-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0005_alter_statusordertranslation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='footwear_type',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KidsStepShop.type'),
        ),
    ]
