# Generated by Django 3.2.9 on 2021-11-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0006_alter_footwear_footwear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='footwear_brend',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KidsStepShop.brend'),
        ),
    ]
