# Generated by Django 3.2.9 on 2021-11-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0007_alter_footwear_footwear_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwear',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='footwear_brend',
            field=models.ForeignKey(default='undefined', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='KidsStepShop.brend'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='footwear_type',
            field=models.ForeignKey(default='undefined', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='KidsStepShop.type'),
        ),
    ]
