# Generated by Django 3.2.9 on 2021-11-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidsStepShop', '0008_auto_20211130_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='footwear_brend',
            field=models.ForeignKey(default='undefined', null=True, on_delete=django.db.models.deletion.CASCADE, to='KidsStepShop.brend'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='footwear_type',
            field=models.ForeignKey(default='undefined', null=True, on_delete=django.db.models.deletion.CASCADE, to='KidsStepShop.type'),
        ),
    ]
